"""Added many-to-many relationship between buyers and in cart products

Revision ID: e1839be1c92d
Revises: 46921699b07c
Create Date: 2019-06-17 15:53:49.640316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1839be1c92d'
down_revision = '46921699b07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('in_carts',
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('bought_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bought_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('in_carts')
    # ### end Alembic commands ###
