"""Modified Product and Review models

Revision ID: e5cd84ce3571
Revises: 6e53fa976d94
Create Date: 2019-06-13 23:58:37.368972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5cd84ce3571'
down_revision = '6e53fa976d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('avg_ratings', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_avg_ratings'), 'product', ['avg_ratings'], unique=False)
    op.drop_index('ix_product_ratings', table_name='product')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'user', ['seller_id'], ['id'])
    op.drop_column('product', 'grading')
    op.drop_column('product', 'ratings')
    op.drop_column('product', 'user_id')
    op.add_column('review', sa.Column('gradings', sa.Float(), nullable=True))
    op.add_column('review', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review', 'product', ['product_id'], ['id'])
    op.drop_column('review', 'grading')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('grading', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'product_id')
    op.drop_column('review', 'gradings')
    op.add_column('product', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('product', sa.Column('ratings', sa.INTEGER(), nullable=True))
    op.add_column('product', sa.Column('grading', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'user', ['user_id'], ['id'])
    op.create_index('ix_product_ratings', 'product', ['ratings'], unique=False)
    op.drop_index(op.f('ix_product_avg_ratings'), table_name='product')
    op.drop_column('product', 'seller_id')
    op.drop_column('product', 'avg_ratings')
    # ### end Alembic commands ###
